name: Run ESLint and test on Pull Requests

on:
  - pull_request

jobs:
  eslint:
    name: Run linters
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out Git repository
      
        uses: actions/setup-node@v1 
      - name: Set up Node.js   
        with:
          node-version: 14
          
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint

  test:
    name: Run Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check out Git repository
      
        uses: actions/setup-node@v1
      - name: Set up Node.js
        with:
          node-version: 14
      - name: Install dependencies
        run: |  
         npm ci  
         npm test

        env:
          CI: true
